name: Machine Learning CI Workflow

on:
  push:
    branches:
      - main  # Trigger jalan setiap kali kamu push ke branch main

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-node-version: '3.10' # Sesuaikan dengan versi python venv-mu

    - name: Install MLflow & Dependencies
      run: |
        pip install mlflow pandas scikit-learn dagshub

    - name: Run MLflow Project Re-training
      env:
        MLFLOW_TRACKING_URI: "https://dagshub.com/mhusenam/Ekperimen_MuhammadHuseinAbdullahMahfud.mlflow"
        MLFLOW_TRACKING_USERNAME: "mhusenam"
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }} # Aman menggunakan GitHub Secrets
      run: |
        cd MLProject
        mlflow run . --no-conda